name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
        publishToNuget:
          description: 'Publish to nuget'
          required: true
          default: true
          type: boolean

jobs:
  build:
    name: "CI : Build, Test and publish"
    runs-on: ubuntu-latest

    steps:
    - id: foo
      uses: MyCIActions@v1
      with:
        githubRef: '${{ github.ref }}'
        githubHeadRef: '${{ github.head_ref }}'
        githubRunNumber: '${{ github.run_number }}'
        nugetPackageIdentifier: '${{ secrets.NUGETPACKAGEIDENTIFIER }}'
        nugetApiKey: '${{ secrets.NUGETAPIKEY }}'
        sonarOrganizationCode: '${{ secrets.SONAR_ORGANIZATION_CODE }}'
        sonarProjectCode: '${{ secrets.SONAR_PROJECT_CODE }}'
        sonarToken: '${{ secrets.SONAR_TOKEN }}'
        publishToNuget: ${{ inputs.publishToNuget }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
