name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
        publishToNuget:
          description: 'Publish to nuget'
          required: true
          default: true
          type: boolean

jobs:
  build:
    name: "CI : Build, Test and publish"
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: buildAndPackDotNet
      uses: mathieumack/MyCIActions/dotnetlibworkflow@v1.8
      with:
        nugetPackageIdentifier: '${{ secrets.NUGETPACKAGEIDENTIFIER }}'
        nugetApiKey: '${{ secrets.NUGETAPIKEY }}'
        sonarOrganizationCode: '${{ secrets.SONAR_ORGANIZATION_CODE }}'
        sonarProjectCode: '${{ secrets.SONAR_PROJECT_CODE }}'
        sonarToken: '${{ secrets.SONAR_TOKEN }}'
        publishToNuget: ${{ inputs.publishToNuget }}
        githubToken: ${{ secrets.GITHUB_TOKEN }}
